[package]
name = "robusta-example"
version = "0.2.2"
authors = ["Giovanni Berti <dev.giovanniberti@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
robusta_jni = { path = "../." }
