name: Release on crates.io
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
      # Allow manual triggering
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    uses: ./.github/workflows/setup_and_test.yml
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Publish release
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
