name: Release on crates.io
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
      # Allow manual triggering
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    uses: ./.github/workflows/setup_and_test.yml
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Publish release
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
