name: Java setup, build and test

on:
  workflow_call:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add $JAVA_HOME to library path
        run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/lib:$JAVA_HOME/lib/server" >> "$GITHUB_ENV"
         elif [ "$RUNNER_OS" == "macOS" ]; then
              echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$JAVA_HOME/lib:$JAVA_HOME/lib/server" >> "$GITHUB_ENV"
         elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "PATH=$PATH;$JAVA_HOME\lib;$JAVA_HOME\lib\server"
              echo "PATH=$PATH;$JAVA_HOME\lib;$JAVA_HOME\lib\server" >> $env:GITHUB_ENV
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
