on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    if: github.event_name != "pull_request" || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    uses: ./.github/workflows/setup_and_test.yml
